<a href="https://colab.research.google.com/github/salazarcristian1014/restaurant-data-analysis/blob/main/RestaurantSalesDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd

Lecturas del archivo
*Loading the dataset*

In [45]:
df = pd.read_csv("Sales-Data-Analysis.csv")

In [46]:
display(df.head())
df.info()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,07-11-2022,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
1,10453,07-11-2022,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
2,10454,07-11-2022,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
3,10455,08-11-2022,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin
4,10456,08-11-2022,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    int64
 1   Date            254 non-null    object
 2   Product         254 non-null    object
 3   Price           254 non-null    float64
 4   Quantity        254 non-null    float64
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 18.0+ KB

Organizamos el formato de la columna fecha para que no sea Object sino datetime64

*Converting the date column format from 'Object' to 'datetime64'*

In [47]:
df['Date'] = pd.to_datetime(df['Date'], format='mixed')

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    int64
 1   Date            254 non-null    datetime64[ns]
 2   Product         254 non-null    object
 3   Price           254 non-null    float64
 4   Quantity        254 non-null    float64
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 18.0+ KB

Luego de revisar lo valores de cada una de las columnas notamos que en la columna 'Manager' habia que hacer una limpieza ya que nos registraban nombres repetidos los cuales pertenecian a una sola persona, esto sucedia ya que habian espacios al principio o mas de un espacio entre nombre y apellido.

Data Cleaning: 'Manager' column
After reviewing the values in each column, we noticed that the 'Manager' column required cleaning. There were duplicated records belonging to the same person due to formatting issues, such as leading spaces or multiple spaces between the first and last names.

In [49]:
df['Manager'] = df['Manager'].str.strip().str.title().str.replace(r'\s+', ' ', regex=True)

In [50]:
df['Manager'].value_counts()

Manager
Tom Jackson      75
Joao Silva       75
Pablo Perez      46
Walter Muller    30
Remy Monet       28
Name: count, dtype: int64

Numero de ordenes por ciudad

*Number of orders per city*

In [51]:
df['City'].value_counts()

City
London    75
Lisbon    75
Madrid    46
Berlin    30
Paris     28
Name: count, dtype: int64

In [52]:
df['Total_Sales'] = df['Price'] * df['Quantity']

creamos la columna de ventas totales para identificar cuales son las ciudades, manager y productos que tienen mayores ventas

*Creating the 'Total_Sales' column to identify top-performing cities, managers, and products*

In [53]:
display(df.head())
df.info()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City,Total_Sales
0,10452,2022-07-11,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London,2000.0143
1,10453,2022-07-11,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid,2199.9920
2,10454,2022-07-11,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon,999.9960
3,10455,2022-08-11,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin,7400.0133
4,10456,2022-08-11,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin,2000.0495

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    int64
 1   Date            254 non-null    datetime64[ns]
 2   Product         254 non-null    object
 3   Price           254 non-null    float64
 4   Quantity        254 non-null    float64
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
 9   Total_Sales     254 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 20.0+ KB

Calculamos las ventas totales de todas las ciudades

*Calculating total sales across all cities*

In [54]:
total = df['Total_Sales'].sum()
print(f"El total de ventas fue de: ${total:,.2f}")

El total de ventas fue de: $769,515.86

Buscamos cual de los manager tiene la mayor cantidad de ventas

*Identifying the manager with the highest sales volume*

In [55]:
df.groupby('Manager')['Total_Sales'].sum().sort_values(ascending=False)

Manager
Joao Silva       241714.1157
Tom Jackson      211201.0406
Pablo Perez      136200.2665
Walter Muller    100600.1313
Remy Monet        79800.3051
Name: Total_Sales, dtype: float64

Agrupamos por ciudad y por Manager para sacar conclusiones y propuestas de mejora

*Grouping by City and Manager to draw conclusions and propose operational improvements*

In [56]:
df.groupby(['Manager', 'City'])['Total_Sales'].agg(['sum', 'mean','count']).style.format("{:,.0f}")

**CONCLUSIONES**

A pesar de que Tom Jackson tuvo las segundas mejores ventas su promedio es uno de los mas bajos. ¿ Por que un promedio bajo si los clientes llegan al restaurante? Falta de asesoria? Falta de preguntas que incentiven a una venta cruzada ?

Walter Muller tiene el mejor promedio a pesar de que tiene una de las ventas mas bajas. ¿Por que las personas no nos visitan en Berlin ? ¿ Falta de publicidad ? ¿ Son las instalaciones del restaurante actractivas para los walk in ? ¿Estan los platos saliendo correctamente ?

Remy monet de Paris tiene un bajo volumen de ventas y adicional a esto tiene uno de los promedios mas bajos.  

Pablo Perez de Madrid tiene un trabajo estable, no son las mejores ventas pero tampoco las peores ademas su promedio se situa en la mitad.

Joao Silva tiene las ventas mas altas y el segundo mejor promedio. Gran trabajo! ¿Que sucederia si envio a Joao de Lisbon a implementar sus practicas por ejemplo en Paris con Remy Monet ?

Si fuera el gerente y luego de revisar estas metricas lo que haria seria llevar a Joao Silva de lisbon a hacer 2 auditorias sobre los procesos que se estan haciendo principalmente en Paris por parte de Remy Monet y mirar que tan viable es el proyecto en Paris.

Luego enviaria a Walter Muller a cada una de las ciudades para que capacitara y entranara a cada manager en como aumentar los tickets promedio.

Luego de eso y despues de un par de semana se revisarian nuevamente los desempeños y se miraria que deciciones seguir tomando.

CONCLUSIONS & ACTION PLAN

Tom Jackson (London): Even though he had the second-best sales volume, his average ticket is one of the lowest. Why is the average so low if customers are coming into the restaurant? Is there a lack of guidance at the table? Is the staff not asking the right questions to encourage cross-selling?

Walter Muller (Berlin): He has the highest average ticket despite having one of the lowest overall sales. Why aren't people visiting us in Berlin? Is it a lack of advertising? Are the restaurant facilities attractive to walk-ins? Are the dishes coming out of the kitchen smoothly to ensure table turnover?

Remy Monet (Paris): Shows a low sales volume and, additionally, one of the lowest average tickets.

Pablo Perez (Madrid): Shows a stable operation. Not the highest sales but not the lowest either, and his average ticket sits right in the middle.

Joao Silva (Lisbon): Has the highest overall sales and the second-best average ticket. Great job! What would happen if I sent Joao from Lisbon to implement his practices in Paris with Remy Monet?

Managerial Decisions:
If I were the operations director, after reviewing these metrics, my immediate action plan would be:

Bring Joao Silva from Lisbon to conduct a couple of audits on the processes currently being handled by Remy Monet in Paris, to evaluate the viability and health of the Parisian location.

Send Walter Muller to each of the other cities to train and coach every manager on upselling techniques to increase their average tickets.

After a couple of weeks, run this exact analysis again to review performance metrics and determine the next strategic decisions.